export const mohZonesSeed = [
  {
    id: 1,
    name: 'Colombo MC',
    district: 'Colombo',
    lat: 6.9271,
    lng: 79.8612,
    riskLevel: 'High',
    activeCases: 450,
    phiDirective: 'Intensive thermal fogging running 6:00 AM - 8:00 AM',
  },
  {
    id: 2,
    name: 'Kaduwela',
    district: 'Colombo',
    lat: 6.9333,
    lng: 79.9833,
    riskLevel: 'Moderate',
    activeCases: 120,
    phiDirective: 'PHIs issuing 7-day clean-up notices in residential areas',
  },
  {
    id: 3,
    name: 'Maharagama',
    district: 'Colombo',
    lat: 6.848,
    lng: 79.9265,
    riskLevel: 'Low',
    activeCases: 45,
    phiDirective: 'Routine weekly inspections',
  },
  {
    id: 4,
    name: 'Dehiwala',
    district: 'Colombo',
    lat: 6.8398,
    lng: 79.8735,
    riskLevel: 'High',
    activeCases: 380,
    phiDirective: 'Emergency drone spraying in canal areas',
  },
  {
    id: 5,
    name: 'Negombo',
    district: 'Gampaha',
    lat: 7.2008,
    lng: 79.8737,
    riskLevel: 'Moderate',
    activeCases: 210,
    phiDirective: 'Coastal cleanup and fumigation active',
  },
  {
    id: 6,
    name: 'Kelaniya',
    district: 'Gampaha',
    lat: 6.9497,
    lng: 79.9167,
    riskLevel: 'High',
    activeCases: 310,
    phiDirective: 'School and religious site inspections priority',
  }
];
