import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import DemoLoginButtons from '../components/auth/DemoLoginButtons';
import FormField from '../components/auth/FormField';
import PasswordField from '../components/auth/PasswordField';
import { useAuth } from '../context/AuthContext';
import { validateLogin } from '../utils/validators';

export default function LoginPage() {
  const [values, setValues] = useState({ email: '', password: '' }); const [errors, setErrors] = useState({}); const [formError, setFormError] = useState(''); const [processing, setProcessing] = useState(false); const { login, demoLogin } = useAuth(); const navigate = useNavigate();
  const update = (event) => setValues((current) => ({ ...current, [event.target.name]: event.target.value }));
  const submit = (event) => { event.preventDefault(); const nextErrors = validateLogin(values); setErrors(nextErrors); setFormError(''); if (Object.keys(nextErrors).length) return; setProcessing(true); if (!login(values.email, values.password)) { setFormError('The email address or password is incorrect.'); setProcessing(false); return; } navigate('/dashboard'); };
  const demo = (role) => { setProcessing(true); demoLogin(role); navigate('/dashboard'); };
  const inputClass = 'w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-slate-900 outline-none transition focus:border-brand-600 focus:ring-3 focus:ring-brand-100';
  return <AuthShell title="Welcome back" subtitle="Sign in to continue supporting safer, healthier communities."><form noValidate onSubmit={submit} className="space-y-4">{formError && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm font-medium text-red-700">{formError}</p>}<FormField id="email" label="Email Address" error={errors.email}><input id="email" name="email" type="email" autoComplete="email" value={values.email} onChange={update} aria-invalid={Boolean(errors.email)} aria-describedby={errors.email ? 'email-error' : undefined} className={inputClass} /></FormField><PasswordField id="password" label="Password" value={values.password} onChange={update} error={errors.password} autoComplete="current-password" /><button disabled={processing} className="w-full rounded-lg bg-brand-700 px-4 py-3 font-bold text-white hover:bg-brand-600 focus:outline-none focus:ring-3 focus:ring-brand-100 disabled:cursor-not-allowed disabled:opacity-60">{processing ? 'Signing in…' : 'Log in'}</button></form><p className="mt-5 text-center text-sm text-slate-600">Don’t have an account? <Link className="font-bold text-brand-700 underline underline-offset-2 focus:outline-none focus:ring-2 focus:ring-brand-600" to="/register">Create one</Link></p><DemoLoginButtons onDemoLogin={demo} disabled={processing} /></AuthShell>;
}
export function AuthShell({ title, subtitle, children }) { return <div className="mx-auto grid min-h-[calc(100vh-73px)] max-w-6xl items-center gap-10 px-4 py-10 sm:px-6 lg:grid-cols-2"><section className="order-2 rounded-2xl bg-brand-700 p-7 text-white lg:order-1 lg:p-10"><p className="text-sm font-bold tracking-widest text-brand-100 uppercase">Dengue hazard reporting</p><h1 className="mt-4 text-4xl font-extrabold tracking-tight sm:text-5xl">SuwaMaga</h1><p className="mt-5 max-w-md text-lg leading-8 text-brand-50">Report risks. Verify hazards. Protect communities.</p><p className="mt-8 text-sm leading-6 text-brand-100">A simple, community-focused way to help identify and respond to local public-health risks.</p></section><section className="order-1 mx-auto w-full max-w-md rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8 lg:order-2"><h2 className="text-2xl font-extrabold text-slate-900">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{subtitle}</p><div className="mt-7">{children}</div></section></div>; }
